In [3]:
import xlwt
def writeinexcel():
    f = open('Ba122_raw_data.txt','r',encoding='utf-8')

if __name__ == "__main__":
  writeinexcel()

In [7]:
import pandas as pd
# txt格式数据分割到excel中
def write_in_excel():
    B = open('Ba122_raw_data.txt','r',encoding='utf-8')
    B_excel = xlwt.Workbook(encoding='utf-8')
    B_excel_1 = B_excel.add_sheet('Raw_Degree')
    B_excel_1.write(0,0,'phi1')
    B_excel_1.write(0,1,'phi')
    B_excel_1.write(0,2,'phi2')
    B_excel_1.write(0,3,'x')
    B_excel_1.write(0,4,'y')
    row = 1
    col = 0
    k = 1
    for lines in B:
        a = lines.strip("\n")
        a = lines.split()
        k+=1
        for i in range(len(a)):
            B_excel_1.write(row,col,a[i])
            col += 1
        row +=1
        col = 0
    B_excel.save("Ba122_calculation.xls")

if __name__ == "__main__":
  write_in_excel()

In [19]:
#删除多余的2-13行，以及暂时不需要的F-N行
###B_excel_2 = pd.read_excel('Ba122_calculation.xls')
#B_excel_2.head()
#B_excel_2.drop(B_excel_2.index[0:9], inplace=True)
#B_excel_2.drop(B_excel_2.columns[4:13], axis = 1, inplace = True)
#print(B_excel_2.head)
#B_excel_2.to_csv("Ba122_calculation_1.xls")

<bound method NDFrame.head of           phi1      phi     phi2           x  Unnamed: 13
9      3.15905  1.62455  4.65916     0.00000          0.0
10     3.15905  1.62455  4.65916     4.00000          0.0
11     3.15905  1.62455  4.65916     8.00000          0.0
12     3.15905  1.62455  4.65148    12.00000          0.0
13     3.15905  1.62455  4.65916    16.00000          0.0
...        ...      ...      ...         ...          ...
19982  2.14675  0.09163  1.01561  1060.00000          0.0
19983  2.32129  0.09058  0.84299  1064.00000          0.0
19984  2.28638  0.10542  0.88523  1068.00000          0.0
19985  2.32129  0.08186  0.84910  1072.00000          0.0
19986  2.28638  0.10542  0.88523  1076.00000          0.0

[19978 rows x 5 columns]>


In [8]:
#上述处理非常麻烦，建议直接将输出的xls表格删除指定列和行，并将数据变成浮点数
import xlrd
import sys
B_excel_2 = pd.read_excel('Ba122_calculation.xls')
for row in B_excel_2:
    values = []
    for column in row[0].split(";"):
        if column.isdigit():
            column = float(column)
        values.append({'number_value': column})
    payload = {
        'row': {'values': values}
        }

print (values)
B_excel_2.info()

[{'number_value': 'y'}]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19978 entries, 0 to 19977
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   phi1    19978 non-null  float64
 1   phi     19978 non-null  float64
 2   phi2    19978 non-null  float64
 3   x       19978 non-null  float64
 4   y       19978 non-null  float64
dtypes: float64(5)
memory usage: 780.5 KB


In [57]:
# 调用Phi1 Phi Phi2数据计算其角度
import numpy as np
import math
#计算每列的角度值
ph1_1 = np.degrees(B_excel_2['phi1'])
phi_1 = np.degrees(B_excel_2['phi'])
phi2_1 = np.degrees(B_excel_2['phi2'])
#print(phi_1)
# 汇总二维列表
phi_all = [ph1_1, phi_1, phi2_1]
phi_all
#phi_all_l = sum(phi_all, []) 
#print(phi_all)
#转化为数组并转置
#phi_all_1 = np.array(phi_all).T
#phi_all_1.shape
#print(phi_all_1)

[0        181.000232
 1        181.000232
 2        181.000232
 3        181.000232
 4        181.000232
             ...    
 19973    122.999715
 19974    133.000120
 19975    130.999924
 19976    133.000120
 19977    130.999924
 Name: phi1, Length: 19978, dtype: float64,
 0        93.079859
 1        93.079859
 2        93.079859
 3        93.079859
 4        93.079859
            ...    
 19973     5.250012
 19974     5.189852
 19975     6.040121
 19976     4.690233
 19977     6.040121
 Name: phi, Length: 19978, dtype: float64,
 0        266.950204
 1        266.950204
 2        266.950204
 3        266.510172
 4        266.950204
             ...    
 19973     58.190167
 19974     48.299769
 19975     50.719943
 19976     48.649846
 19977     50.719943
 Name: phi2, Length: 19978, dtype: float64]

In [39]:
# 检查数据类型
phi_all_1.dtype

dtype('float64')

In [62]:
def transpose_2d(data):
    transposed = [[row[i] for row in data] for i in range(len(data[0]))]
    return transposed
phi_all_T = transpose_2d(phi_all)
#print(phi_all_T)
#转为数组
phi_all_T_1 = np.array(phi_all_T)
phi_all_T_1.shape

(19978, 3)

In [65]:
from scipy.spatial.transform import Rotation as R

for i in range(len(phi_all_T_1)):
    i = 0
    phi_all_matrix = R.from_euler('xyz', phi_all_T_1[i:, :], degrees = True)
    i = i + 1 
#ph1_1_matrix = R.from_euler('x', ph1_1, degrees = True)
#ph1_1_matrix_1 = ph1_1_matrix.as_matrix()
#print(phi_1_matrix_1)

#phi_1_matrix = R.from_euler('y', phi_1, degrees = True)
#phi_1_matrix_1 = phi_1_matrix.as_matrix()

#phi2_1_matrix = R.from_euler('z', phi2_1, degrees = True)
#phi2_1_matrix_1 = phi2_1_matrix.as_matrix()

#phi_matrix_all = [ph1_1_matrix_1, phi_1_matrix_1, phi2_1_matrix_1]
#print(phi_matrix_all)

In [75]:
phi_all_euler = phi_all_matrix.as_euler('zxy', degrees = True)
#print(phi_all_euler)
#phi_all_euler.shape

[[ 37.23172028 -84.91263625  52.71314918]
 [ 37.23172028 -84.91263625  52.71314918]
 [ 37.23172028 -84.91263625  52.71314918]
 ...
 [114.68984976  32.09008968 140.36038177]
 [118.46761927  31.67075977 143.0015731 ]
 [114.68984976  32.09008968 140.36038177]]


(19978, 3)

In [83]:
# 数组筛选，1. 考虑正负 如果负 alpha和beta角度180-原角度。如果grama 负 ➕90 度
# 排序
import numpy as np
matrix1 = phi_all_euler[:,[0]]
matrix2 = phi_all_euler[:,[1]]
matrix3 = phi_all_euler[:,[2]]
#print(matrix1)
# 拆分数组
matrix1_1 = matrix1 < 0
matrix2_1 = matrix2 < 0
matrix3_1 = matrix3 < 0

# print(matrix1_1)
matrix1[matrix1_1] = 180 + matrix1[matrix1_1]        
# print(matrix1)
matrix2[matrix2_1] = 180 + matrix1[matrix2_1]
matrix3[matrix3_1] = 0-matrix1[matrix3_1] 
# print(matrix3)

[[ 52.71314918]
 [ 52.71314918]
 [ 52.71314918]
 ...
 [140.36038177]
 [143.0015731 ]
 [140.36038177]]


In [102]:
# 大于180
matrix11 = phi_all_T_1[:,[0]]
matrix12 = phi_all_T_1[:,[1]]
matrix13 = phi_all_T_1[:,[2]]
matrix1_2 = matrix11 > 180
matrix2_2 = matrix12 > 180
matrix3_2 = matrix13 > 180
matrix11[matrix1_2] = matrix11[matrix1_2] - 180        
print(matrix11)
matrix12[matrix2_2] = matrix12[matrix2_2] - 180
matrix13[matrix3_2] = matrix13[matrix3_2] - 180

[[  1.00023227]
 [  1.00023227]
 [  1.00023227]
 ...
 [130.99992436]
 [133.00012003]
 [130.99992436]]


In [111]:
# 合并数组
phi_all_euler_sort = np.concatenate((matrix11, matrix12, matrix13, matrix1, matrix2, matrix3), axis = 1)
# print(phi_all_euler_sort)
# 多维数组排序
phi_all_euler_sort_r = phi_all_euler_sort[np.argsort(-phi_all_euler_sort[:, 4], ), :]
print(phi_all_euler_sort_r)

[[2.00004362e+00 9.05800437e+01 8.91801558e+01 1.68372903e+02
  1.68372903e+02 1.16270966e+01]
 [2.00019566e+00 8.87998639e+01 8.61797279e+01 1.16449894e+01
  1.68355011e+02 7.83359241e+01]
 [2.00019566e+00 8.87998639e+01 8.61797279e+01 1.16449894e+01
  1.68355011e+02 7.83359241e+01]
 ...
 [1.10000647e+01 2.00993595e+00 8.03802491e+01 8.01751517e+01
  1.17930938e-01 8.01751517e+01]
 [1.10000647e+01 2.00993595e+00 8.03802491e+01 8.01751517e+01
  1.17930938e-01 8.01751517e+01]
 [1.10000647e+01 2.00993595e+00 8.03802491e+01 8.01751517e+01
  1.17930938e-01 8.01751517e+01]]


In [114]:
#写入excel表格
import pandas as pd
phi_all_euler_sort_r_df = pd.DataFrame(phi_all_euler_sort_r)
writer = pd.ExcelWriter('result.xlsx')
phi_all_euler_sort_r_df.to_excel(writer,'page_1', float_format = '%.5f')
writer.save()